# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Text-DeDuper
version:      1.00
version_from: lib/Text/DeDuper.pm
installdirs:  site
requires:
    Digest::MD4:                   1.5
    Encode:                        2.12

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
